---
stunnel_debug_level: 7
stunnel_user: stunnel4
stunnel_group: stunnel4
stunnel_log: /var/log/stunnel4/stunnel.log
stunnel_pid: /var/run/stunnel4/stunnel.pid
stunnel_cert: /etc/stunnel/cert.pem
stunnel_verify_level: 2
stunnel_ca_path: /etc/ssl/certs
stunnel_crl_path: /etc/ssl/certs
stunnel_ssl_options: 'NO_SSLv2'
